TERMINAL LIST
Type:      File
Name:      f1
Original:  <dir>/r4/f1
Created:   2020-05-31 12:00:00 
Entries:      1
Total Files:  1
Log size:     0.00B
Size:         10.00B 


EXCEPTION RESTORE
Encountered exception(s)

- Cannot restore the trash file 'f1' as one exists at the original location: <dir>/r4/f1

CallStack (from HasCallStack):
  getCallStack, called at src/SafeRm/Effects/MonadCallStack.hs:47:13 in <package>:SafeRm.Effects.MonadCallStack
  throwCS, called at src/SafeRm/Data/PathData.hs:293:5 in <package>:SafeRm.Data.PathData
  mvTrashToOriginal, called at src/SafeRm.hs:290:9 in <package>:SafeRm
  restore, called at src/SafeRm/Runner.hs:139:24 in <package>:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:227:36 in <package>:Functional.Prelude


CallStack (from HasCallStack):
  getCallStack, called at src/SafeRm/Effects/MonadCallStack.hs:47:13 in <package>:SafeRm.Effects.MonadCallStack
  throwCS, called at src/SafeRm.hs:307:5 in <package>:SafeRm
  restore, called at src/SafeRm/Runner.hs:139:24 in <package>:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:227:36 in <package>:Functional.Prelude

LOGS RESTORE
[2020-05-31 12:00:00][functional.restore][Debug] Trash home: <dir>/r4/.trash
[2020-05-31 12:00:00][functional.restore.readIndex][Debug] Index path: <dir>/r4/.trash/.index.csv
[2020-05-31 12:00:00][functional.restore.readIndex.readIndexWithFold][Debug] Found: MkPathData {pathType = PathTypeFile, fileName = MkPathI {unPathI = "f1"}, originalPath = MkPathI {unPathI = "<dir>/r4/f1"}, created = MkTimestamp {unTimestamp = 2020-05-31 12:00:00}}
[2020-05-31 12:00:00][functional.restore.restoring][Debug] MkPathData {pathType = PathTypeFile, fileName = MkPathI {unPathI = "f1"}, originalPath = MkPathI {unPathI = "<dir>/r4/f1"}, created = MkTimestamp {unTimestamp = 2020-05-31 12:00:00}}
[2020-05-31 12:00:00][functional.restore.restoring][Warn] Cannot restore the trash file 'f1' as one exists at the original location: <dir>/r4/f1

CallStack (from HasCallStack):
  getCallStack, called at src/SafeRm/Effects/MonadCallStack.hs:47:13 in <package>:SafeRm.Effects.MonadCallStack
  throwCS, called at src/SafeRm/Data/PathData.hs:293:5 in <package>:SafeRm.Data.PathData
  mvTrashToOriginal, called at src/SafeRm.hs:290:9 in <package>:SafeRm
  restore, called at src/SafeRm/Runner.hs:139:24 in <package>:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:227:36 in <package>:Functional.Prelude
[2020-05-31 12:00:00][functional.restore][Info] Restored: 
[2020-05-31 12:00:00][functional][Error] Encountered exception(s)

- Cannot restore the trash file 'f1' as one exists at the original location: <dir>/r4/f1

CallStack (from HasCallStack):
  getCallStack, called at src/SafeRm/Effects/MonadCallStack.hs:47:13 in <package>:SafeRm.Effects.MonadCallStack
  throwCS, called at src/SafeRm/Data/PathData.hs:293:5 in <package>:SafeRm.Data.PathData
  mvTrashToOriginal, called at src/SafeRm.hs:290:9 in <package>:SafeRm
  restore, called at src/SafeRm/Runner.hs:139:24 in <package>:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:227:36 in <package>:Functional.Prelude


CallStack (from HasCallStack):
  getCallStack, called at src/SafeRm/Effects/MonadCallStack.hs:47:13 in <package>:SafeRm.Effects.MonadCallStack
  throwCS, called at src/SafeRm.hs:307:5 in <package>:SafeRm
  restore, called at src/SafeRm/Runner.hs:139:24 in <package>:SafeRm.Runner
  runCmd, called at test/functional/Functional/Prelude.hs:227:36 in <package>:Functional.Prelude


